#!/bin/bash
set -e

die() { echo "$*" >&2; exit 1; }

cd ./exercises/practice

exercises=()
if [[ -n "$1" ]]; then
    [[ -d "$1" ]] || die "Error: not an exercise slug: $1"
    exercises=("$1")
else
    readarray -t exercises < <(
        find . -maxdepth 1 -mindepth 1 -type d -printf '%f\n'
    )
fi

for dir in "${exercises[@]}"; do
    cd "$dir"
    echo "Running $dir ..."

    # validate package name
    name="exercism/$dir"
    if ! grep -qE "^ *name .+\"$name\"" package.wren; then
        die "package.wren: wrong name, should be: $name"
    fi

    # test it
    solution=$(jq -r ".files .solution[0]" .meta/config.json)
    example=$(jq -r ".files .example[0]" .meta/config.json)
    spec=$(jq -r ".files .test[0]" .meta/config.json)
    rm -rf .tmp
    mkdir -p .tmp
    cd .tmp
    cp ../*.wren .
    sed -i'' -e 's/skip.test/do.test/' "$spec"
    cp "../$example" "$solution"
    ln -s ../../../../vendor vendor
    wrenc "$spec"
    cd ..
    rm -rf .tmp
    cd ..
done
